#!/usr/bin/env bash
# gen-secrets.sh [--force] — create .env from .env.example and fill in its secrets:
# JWT_SECRET (48 random bytes) and a demo client secret whose SHA-256 is the only form stored
# in .env; the plaintext is shown once and written to .env.demo-credentials for the e2e scripts.
# Idempotent: without --force it only fills placeholders. --force rotates both, killing every
# issued token.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env"
ENV_EXAMPLE="${ROOT_DIR}/.env.example"
CREDS_FILE="${ROOT_DIR}/.env.demo-credentials"
PLACEHOLDER_PREFIX="CHANGE_ME_"
FORCE=0

log()  { printf '\033[36m==>\033[0m %s\n' "$*"; }
die()  { printf '\033[31m[error]\033[0m %s\n' "$*" >&2; exit 1; }

case "${1:-}" in
  --force) FORCE=1 ;;
  -h | --help) sed -n '2,6p' "$0"; exit 0 ;;
  "") ;;
  *) die "unknown argument: $1 (expected --force)" ;;
esac

command -v openssl >/dev/null 2>&1 || die "openssl is required"
command -v sha256sum >/dev/null 2>&1 || die "sha256sum is required"

# set_env_var KEY VALUE FILE — replaces the KEY= line in place, or appends it.
set_env_var() {
  local key="$1" value="$2" file="$3" escaped
  escaped="$(printf '%s' "${value}" | sed -e 's/[\\|&]/\\&/g')"
  if grep -qE "^${key}=" "${file}"; then
    sed -i -E "s|^${key}=.*|${key}=${escaped}|" "${file}"
  else
    printf '%s=%s\n' "${key}" "${value}" >> "${file}"
  fi
}

# get_env_var KEY FILE — last value of KEY, empty if absent.
get_env_var() {
  grep -E "^$1=" "$2" 2>/dev/null | tail -n 1 | cut -d= -f2- || true
}

needs_value() { # missing, or still a CHANGE_ME_ placeholder
  local current="$1"
  [ -z "${current}" ] || [ "${current#"${PLACEHOLDER_PREFIX}"}" != "${current}" ]
}

if [ ! -f "${ENV_FILE}" ]; then
  [ -f "${ENV_EXAMPLE}" ] || die "missing ${ENV_EXAMPLE}"
  log "creating .env from .env.example"
  cp "${ENV_EXAMPLE}" "${ENV_FILE}"
  chmod 600 "${ENV_FILE}"
else
  log ".env already exists, updating it in place"
fi

current_jwt="$(get_env_var JWT_SECRET "${ENV_FILE}")"
if [ "${FORCE}" -eq 1 ] || needs_value "${current_jwt}"; then
  set_env_var JWT_SECRET "$(openssl rand -base64 48)" "${ENV_FILE}"
  log "JWT_SECRET generated (48 random bytes, base64)"
else
  log "JWT_SECRET already set, keeping it (use --force to rotate)"
fi

current_hash="$(get_env_var AUTH_CLIENT_SECRET_SHA256 "${ENV_FILE}")"
client_id="$(get_env_var AUTH_CLIENT_ID "${ENV_FILE}")"
client_id="${client_id:-demo-client}"

if [ "${FORCE}" -eq 1 ] || needs_value "${current_hash}" || [ ! -f "${CREDS_FILE}" ]; then
  client_secret="$(openssl rand -hex 24)"
  secret_hash="$(printf '%s' "${client_secret}" | sha256sum | cut -d' ' -f1)"
  set_env_var AUTH_CLIENT_ID "${client_id}" "${ENV_FILE}"
  set_env_var AUTH_CLIENT_SECRET_SHA256 "${secret_hash}" "${ENV_FILE}"

  umask 077
  cat > "${CREDS_FILE}" <<CREDS
# Generated by scripts/gen-secrets.sh — gitignored, NEVER commit this file.
# Plaintext demo credentials for scripts/e2e-smoke.sh and scripts/demo.sh (the SPA uses the demo token).
AUTH_CLIENT_ID=${client_id}
AUTH_CLIENT_SECRET=${client_secret}
CREDS
  chmod 600 "${CREDS_FILE}"

  cat <<BANNER

  ┌──────────────────────────────────────────────────────────────────────────┐
  │  DEMO CLIENT CREDENTIALS — shown only once, only the SHA-256 is stored.   │
  └──────────────────────────────────────────────────────────────────────────┘

    clientId     : ${client_id}
    clientSecret : ${client_secret}

  Use them with curl, Swagger UI and in:

    curl -sS -X POST http://localhost:8080/api/v1/auth/token \\
      -H 'Content-Type: application/json' \\
      -d '{"clientId":"${client_id}","clientSecret":"${client_secret}"}'

  They are also saved to .env.demo-credentials (gitignored, mode 600).
  Lost it? Run ./scripts/gen-secrets.sh --force to issue a new one.

BANNER
else
  log "AUTH_CLIENT_SECRET_SHA256 already set; plaintext is in .env.demo-credentials (--force to rotate)"
fi

log "done. Next: make up"
